"""reward auto fulfill

Revision ID: 0b27fca8f36b
Revises: 770cdebc49ee
Create Date: 2026-06-05 19:24:00.919306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b27fca8f36b'
down_revision: Union[str, Sequence[str], None] = '770cdebc49ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.alter_column('auto_fulfill',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.alter_column('auto_fulfill',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
